[[constraint]]
  name = "github.com/jinzhu/gorm"

[[constraint]]
  name = "github.com/broderickhyman/albiondata-sql"

[[constraint]]
  name = "github.com/mitchellh/go-homedir"

[[constraint]]
  name = "github.com/spf13/cobra"

[[constraint]]
  name = "github.com/spf13/viper"

[[constraint]]
  name = "github.com/labstack/echo"
